FROM public.ecr.aws/lambda/python:3.12

# Install dependencies
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY run_pipeline.py ${LAMBDA_TASK_ROOT}/
COPY config.py ${LAMBDA_TASK_ROOT}/
COPY alpaca_extract.py ${LAMBDA_TASK_ROOT}/
COPY alpaca_transform_cleaning.py ${LAMBDA_TASK_ROOT}/
COPY alpaca_load.py ${LAMBDA_TASK_ROOT}/
COPY top_100_tech_companies.py ${LAMBDA_TASK_ROOT}/
COPY logger.py ${LAMBDA_TASK_ROOT}/
COPY rag_ingest_invoke.py ${LAMBDA_TASK_ROOT}/

RUN curl -o ${LAMBDA_TASK_ROOT}/global-bundle.pem https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

CMD ["run_pipeline.lambda_handler"]