FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY fallback_stock.py .

COPY rss_pipeline.py .

COPY rss_extract_live.py .

COPY rss_analysis.py .

COPY rss_transform.py .

COPY rss_load.py .

CMD ["rss_pipeline.lambda_handler"]