FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY rss_pipeline.py .

COPY rss_extract.py .

COPY rss_transform.py .

COPY rss_load.py .

CMD ["rss_lambda_handler.lambda_handler"]